name: Java CI with Maven

on: [push, pull_request]

jobs:
  ubuntu-adopt-jdk-11:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "adopt"
          cache: maven
      - name: Build with Maven
        run: mvn package --file pom.xml

  ubuntu-adopt-jdk-17:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
          cache: maven
      - name: Build with Maven
        run: mvn package --file pom.xml

  ubuntu-adopt-jdk-21:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "adopt"
          cache: maven
      - name: Build with Maven
        run: mvn package --file pom.xml
